// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiJodzjv6gHWVBepPFfhXWPWuq7WiazmE',
    appId: '1:883473585633:web:2bb3fa6f2b6e1adc426ea0',
    messagingSenderId: '883473585633',
    projectId: 'bluff-master-61e30',
    authDomain: 'bluff-master-61e30.firebaseapp.com',
    storageBucket: 'bluff-master-61e30.firebasestorage.app',
    measurementId: 'G-333WJTKLX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCad0vSVRLsRSP8_-dJjItSmBOW4gdWFsQ',
    appId: '1:883473585633:android:4498a66a2795c83a426ea0',
    messagingSenderId: '883473585633',
    projectId: 'bluff-master-61e30',
    storageBucket: 'bluff-master-61e30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDckm_iDxcujWPBWFox7q5YmBPm2Fx_QLQ',
    appId: '1:883473585633:ios:b2d9465ad0b42c3d426ea0',
    messagingSenderId: '883473585633',
    projectId: 'bluff-master-61e30',
    storageBucket: 'bluff-master-61e30.firebasestorage.app',
    iosBundleId: 'com.example.bluffMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDckm_iDxcujWPBWFox7q5YmBPm2Fx_QLQ',
    appId: '1:883473585633:ios:b2d9465ad0b42c3d426ea0',
    messagingSenderId: '883473585633',
    projectId: 'bluff-master-61e30',
    storageBucket: 'bluff-master-61e30.firebasestorage.app',
    iosBundleId: 'com.example.bluffMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiJodzjv6gHWVBepPFfhXWPWuq7WiazmE',
    appId: '1:883473585633:web:616503f72920cc31426ea0',
    messagingSenderId: '883473585633',
    projectId: 'bluff-master-61e30',
    authDomain: 'bluff-master-61e30.firebaseapp.com',
    storageBucket: 'bluff-master-61e30.firebasestorage.app',
    measurementId: 'G-ZXBTE4GS5D',
  );
}
